### ISSUE TITLE
Update the carousel

### ISSUE THREAD

**Issue by Prakhar-Shankar** [JIITODC/website-24#23]
Currently the crousel is showing only one photograph, kindly update that.

**Comment by TusharSin810** [comment]
Changed the carousel Completely . 
![Screenshot from 2024-09-26 08-31-23](https://github.com/user-attachments/assets/2e88510c-08c3-476d-9ff0-19f1af11171d)

**Comment by SOURHEAD** [comment]
https://github.com/JIITODC/website-24/pull/25
updated here, content to be added
also the arrows are misaligned, can it be mouse hover-activated?
